name = "DalyNotebook"
uuid = "dbea37f4-0c25-4c77-b5a2-d63b3a816163"
authors = ["Jędrzej Lewandowski <jedrzejblew@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
